### ISSUE TITLE
show SMS received on kalkun ?

### ISSUE THREAD

**Issue by ghost** [kalkun-sms/Kalkun#130]
Hello, well why i can show on kalkun all sms i received ?

i can send sms but now way to show the sms received on my phone ?

can u have issue for this please

**Comment by sugengstiki** [comment]
must be set the Telephone Number in Settings menu. Only user with this Telephone Number can receive message

**Comment by tenzap** [comment]
If you don't see the sms appear in the inbox table, then the issue does very likely lie somewhere in gammu or gammu configuration. gammu apparently can't insert the message in the database, thus it can't be processed by kalkun (processing is triggered by runonreceive in gammu config). If kalkun has nothing to process no message is displayed.

-> closing
