### ISSUE TITLE
Regarding the plugins you have as a package

### ISSUE THREAD

**Issue by derikitz** [kalkun-sms/Kalkun#152]
Some of your plugins(sms_to_email, sms_autoreply) are blocking the daemon/message_routine which is why most sent messages aren't displayed.
Can you try updating your plugins?

**Comment by tenzap** [comment]
This is probably fixed by https://github.com/kalkun-sms/Kalkun/pull/331

If this is still present, please create a new issue with detailed steps to reproduce and the error/stacktrace reported.
