### ISSUE TITLE
Why incoming message on mysql exist but not kalkun inbox

### ISSUE THREAD

**Issue by shaddana** [kalkun-sms/Kalkun#155]
Dear Om Arie and All,

I try send message to my message server, the message received on mysql but can't see on kalkun inbox, when I check on mysql the value "Processed" is "false" should be "true" right so the message can see on kalkun inbox.

Any or anyone have idea how to fixed?, thank you

**Comment by whitehunter** [comment]
Solution for me: 
in /etc/gammu-smsdrc
specify daemon.sh location:
runonreceive = /var/www/html/kalkun/scripts/daemon.sh

and in daemon.sh you should set location of daemon.php

cat /var/www/html/kalkun/scripts/daemon.sh
#!/bin/sh

# Configure this (use absolute path)
PHP=/usr/bin/php # php cli path
DAEMON=/var/www/html/kalkun/scripts/daemon.php # daemon.php path
# Execute

**Comment by tenzap** [comment]
@whitehunter 's answer is correct.

Another option would be to go to http://localhost/kalkun-git/index.php/daemon/message_routine/
