### ISSUE TITLE
Kalkun external_script: multipart messages ignored

### ISSUE THREAD

**Issue by mvromanenkov** [kalkun-sms/Kalkun#180]
On receiving a multipart message the "external script" plugin handles only the first part. It's necessary to merge the parts into a solid string and pass it for further handling.

**Comment by tenzap** [comment]
Is the full incoming message displayed in Kalkun's inbox?
Is the full incoming message stored in the filed "TextDecoded" of inbox table in the database?

I found through that: the content passed to the external_script is the content of the field "TextDecoded".
On my test, I sent with python-gammu a test SMS of 800 chars, and the database only stored 160 chars.
If I put a longer message into that field, the full longer message is also passed to the external_script.

I would need to test with an incoming message on a real device but I have no real device connected to gammu. 

If by chance you could check if the message in the database has full content, then issue may be in kalkun.
If only 160 chars are stored in the DB, then then problem is most likely in gammu which stores the message truncated.

**Comment by mvromanenkov** [comment]
It was so nice to have an answer after 5 years! But I already solved the problem here: https://php.ru/forum/threads/kalkun-sms-kak-soedinit-sostavnye-soobschenija.67584/#post-547340
It's a Russian forum, but I hope google.translate will help.

Unfortunately, I don't have any chance to test your solution now. The company is alredy dead, the project too.

But anyway, thanx for the feedback!

**Comment by tenzap** [comment]
I ended up connected a phone and sending this test sms
```
200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432
```

Result is the message is stored  in inbox as 7 records (gammu processing). TextDecoded field of the 1st message contains the full text above, the 6 subsquent messages have an empty "TextDecoded".

In debugging mode, the $sms object passed to external_script plugin contains the complete Text Decoded.

So the full text is stored in the DB in the 1st record, displayed fully in the GUI and textDecoded received by external_script is also complete.

Probably this got fixed in the meantime. If anyone is still facing the issue, please reopen.

For now, I close.
