### ISSUE TITLE
pbk groups are not displayed when adding contact

### ISSUE THREAD

**Issue by tenzap** [kalkun-sms/Kalkun#243]
Go to phonebook
Click "Add contact"
Select "Using Contact Form"
At the bottom of the popup there is a section "group/select group"
But this one is empty, although a pbk groups have been created
I guess it should list the available groups (not sure)

**Comment by kingster** [comment]
Closing, duplicate #244

**Comment by kingster** [comment]
Its an auto suggest field, try typing into it.

**Comment by tenzap** [comment]
ok ! it works
Maybe the label should be changed to something like "start typing the name of group"
Actually, having the possible groups listed makes life easier when on doesn't remember the group names (like me :D)

**Comment by kingster** [comment]
Yes, that can be a feature enhancement :)

**Comment by tenzap** [comment]
See PR #245 for label change
