### ISSUE TITLE
PHP Warning when calling REST API

### ISSUE THREAD

**Issue by Sergio-** [kalkun-sms/Kalkun#252]
I'm getting a PHP Warning message (see below) on my REST API responses. API works fine, however the response contains this warning message, instead of the pure JSON string.
See below:
```

<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Warning</p>
<p>Message:  Creating default object from empty value</p>
<p>Filename: libraries/REST_Controller.php</p>
<p>Line Number: 103</p>


</div>{"status":"Message queued","phoneNumber":"994867801","message":"Nova"}
```
Any ideas on how to get it fixed?
Thanks.

**Comment by Sergio-** [comment]
@kingster Any idea if this is something that can be fixed? Thank you.

**Comment by tenzap** [comment]
@Sergio- could you check again and report back if you are still facing that issue with latest devel branch?

**Comment by Sergio-** [comment]
Hello @tenzap. Thanks for the reply.
Unfortunately, I don't have access to that infrastructure anymore, It's being with a different administrator for over an year now. So, unfortunately, I cannot test it neither get more info.
Thanks for the update. I really hope it's useful for new installs now.
Best Regards,
