### ISSUE TITLE
White Screen Page

### ISSUE THREAD

**Issue by rpermana76** [kalkun-sms/Kalkun#255]
i have white screen page when trying to open kalkun (version 0.7.1 / 0.7 / 0.6 at localhost. no errors notification.
Please Help.
Thank You...

**Comment by tparvais** [comment]
same issue

**Comment by santhony2** [comment]
Try lowering your version of php to 5.6.21

**Comment by tenzap** [comment]
If your system runs a version of PHP >= 7.x Please use the devel branch https://github.com/back2arie/Kalkun/tree/devel

**Comment by kingster** [comment]
This is now resolved with latest devel.
