### ISSUE TITLE
Install without php-session causes error BEFORE Kalkun does checks

### ISSUE THREAD

**Issue by realJoshByrnes** [kalkun-sms/Kalkun#262]
An uncaught Exception was encountered
Type: Error
Message: Call to undefined function session_save_path()
Filename: /var/www/application/config/config.php
Line Number: 253

**Comment by tenzap** [comment]
Please close the issue, this is fixed in https://github.com/kalkun-sms/Kalkun.

Kalkun is now being maintained at a new home. Please head over to https://github.com/kalkun-sms/Kalkun for the latest version.
