### ISSUE TITLE
No error for message compose failure

### ISSUE THREAD

**Issue by realJoshByrnes** [kalkun-sms/Kalkun#266]
This happens when the message is unable to be stored in the database.

Currently it's happening with some valid UTF-8 strings - see #265 (will be fixed shortly)
It would likely happen for various reasons, including a disconnection between browser and Kalkun.

On error, there should be a notification indicating the message was unable to be sent, and the loading indicator should disappear.

**Comment by tenzap** [comment]
Is this fixed in devel since the recent merges? Could you please close the issue in that case? Thanks.
