### ISSUE TITLE
Bug in max_sms_sent_by_minute config option & compose send date

### ISSUE THREAD

**Issue by pjunyent** [kalkun-sms/Kalkun#29]
EXPECTED BEHAVIOUR:
SMS would be sent starting at the set date and time, in the intervals set in config (e.g. If set to a max of 1 SMS/min, and queued 50 SMS for tomorrow at 12:00, it should queue one SMS for every minute between 12:00 and 12:50)

BUG BEHAVIOUR
SMS queued with "send date = at date and time" and config option [max_sms_sent_by_minute] active, are queued for the interval set at the config option, but are queued to be sent starting at that moment (e.g. If set 1 SMS/min, & queued 50 SMS at 11:00 for 12:00, it will queue 50 SMS spaced by 1 min, but it will start sending them at 11:00, ignoring the specified "at date and time" option).

STEPS TO REPRODUCE
Set in /kalkun_settings.php; $config['max_sms_sent_by_minute'] = i; with i=/=0
Navigate to  Kalkun's URL and log in
Compose message from file, setting "Send date" to "At date and time"
Check outbox to see pending SMS are not correctly queued.

(Is there anyway to queue SMS's send time by file? Like when we select number from the .csv, can we also specify there the desired sending time?)

**Comment by tenzap** [comment]
Could you test the patch in kalkun-sms#30 and report back if that fixes your issue ?

**Comment by pjunyent** [comment]
Applied fix to messages.php & it works perfectly fine, as expected :)
Thx, I was already trying to patch it and submit a PR, but you outperformed me.
