### ISSUE TITLE
White page after login even with last dev version

### ISSUE THREAD

**Issue by Ciruello** [kalkun-sms/Kalkun#466]
CI_ENV is setted to developer but no errors are displaying, last kalkun dev version is installed as reported in the similar closed topic, I'm running kalkun on a mysql server with php version 8.1.5

![Immagine 2022-05-11 153545](https://user-images.githubusercontent.com/105368177/167862785-f72c6eb8-4014-41c7-8ff6-4ef6b53a2ad6.png)

**Comment by tenzap** [comment]
Did you follow the [installation instructions of the wiki](https://github.com/kalkun-sms/Kalkun/wiki/Installation) and especially did you install all the dependencies with composer?
