### ISSUE TITLE
Phone format check error with 3 comma separated numbers

### ISSUE THREAD

**Issue by pjunyent** [kalkun-sms/Kalkun#478]
**Describe the bug**
When sending sms manually ("input manually") to 3 or more spanish numbers (format 600000000 or +34600000000) separated by commas this error happens: "The string supplied did not seem to be a phone number."

**To Reproduce**
1. Go to kalkun main page.
2. Click on "compose".
3. Select "input manually"
4. Write in the input box 3 or more spanish numbers (e.g. "+34600000000, +34600000000, +34600000000")
5. Red error message: "The string supplied did not seem to be a phone number."

**Expected behavior**
You should be able to send messages to 3 or more spanish numbers.

**Screenshots**
![Captura desde 2022-10-12 11-42-02](https://user-images.githubusercontent.com/64863210/195323896-dcd447c6-31d6-4055-9de3-3dd3c099dae1.png)

**Browser, kalkun setup, database setup..:**
* Kalkun version: `0.8.0-rc-1 [Lang: spanish] [CountryCode: ES]`
* Operating system: `Linux kalkunpod 5.14.0-70.26.1.el9_0.x86_64 #1 SMP PREEMPT Tue Sep 20 17:53:31 UTC 2022 x86_64`
* PHP Version: `8.0.24`
* DB Backend: `MySQLi 10.9.3-MariaDB-1:10.9.3+maria~ubu2204 (mysqli)`
* Gammu version: `Gammu 1.42.0, Linux, kernel 5.14.0-70.26.1.el9_0.x86_64 (#1 SMP PREEMPT Tue Sep 20 17:53:31 UTC 2022), GCC 11.2`
* Gammu DB schema: `17`
* Browser: `Chrome 106.0.0.0`
* Plugins: ``

**Additional context**
Error happens at /application/helpers/kalkun_helper.php, line 448. It seems related to kalkun's implementation of `\libphonenumber` being unable to recognised the string as three valid phone numbers.
I was able to bypass this issue by running this commands through my dockerfile & it worked, albeit it did not check the phonenumber format obviously: 
```
RUN /bin/busybox sed -i "s|tr(\'Please specify a valid mobile phone number\')|TRUE|g" /var/www/application/helpers/kalkun_helper.php \  
&& /bin/busybox sed -i "s|\$e->getMessage()|TRUE|g" /var/www/application/helpers/kalkun_helper.php
```

**Comment by tenzap** [comment]
May you please check if the last commit (https://github.com/kalkun-sms/Kalkun/commit/1e1745597e5ec6f05dc274d1af03b468b3a7639c)  on https://github.com/kalkun-sms/Kalkun/tree/fix-478
- fixes your issue
- doesn't bring a regression

**Comment by pjunyent** [comment]
Works great, thaks for the fix!

**Comment by tenzap** [comment]
Reopen, until this is pushed to devel (after 0.8.0 release).
